name       : libptytty
version    : 2.0
release    : 1
source     :
    - http://dist.schmorp.de/libptytty/libptytty-2.0.tar.gz : 8033ed3aadf28759660d4f11f2d7b030acf2a6890cb0f7926fb0cfa6739d31f7
license    : GPL-2.0-or-later 
component  : programming.library
summary    : A library for OS-independent pseudo-TTY management.
description: |
    A library for OS-independent pseudo-TTY management.
setup      : |
    %cmake_ninja \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DBUILD_SHARED_LIBS=ON 
build      : |
    %ninja_build
install    : |
    %ninja_install
